### ISSUE TITLE
Adaptivity bug

### ISSUE THREAD

**Issue by nosovk** [andriytyurnikov/andriytyurnikov.me#1]
<img width="769" alt="image" src="https://github.com/andriytyurnikov/andriytyurnikov.me/assets/1398808/a84ac192-0a5c-4e1e-9feb-e9eec47d22e7">
at 1020x660px content incorrectly positioned.

**Comment by andriytyurnikov** [comment]
What kind of device is it?

**Comment by nosovk** [comment]
Chrome Version 120.0.6099.71 (Official Build) (64-bit)
Windows 11

**Comment by andriytyurnikov** [comment]
Thanks, @nosovk, good catch. Unfortunately, I confirm reproduction for Windows Chrome and Edge.

Windows FireFox and MacOS Chrome are fine though :/

<img width="919" alt="Screenshot 2023-12-12 at 10 47 56" src="https://github.com/andriytyurnikov/andriytyurnikov.me/assets/3668/33b61b0c-d145-4d10-9e6a-f5dd1b539631">

It is like back in 1999

**Comment by andriytyurnikov** [comment]
Fixed
